version: "3"

services:

  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "80:80"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2

  mysql:
    build: ./bin/mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rta
      MYSQL_USER: rlozach
      MYSQL_PASSWORD: infopro

  phpmyadmin:
    container_name: 'phpmyadmin'
    links:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "81:80"
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      #PMA_USER: rlozach
      #PMA_PASSWORD: infopro