<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuxwcwy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuxwcwy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIuxwcwy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIuxwcwy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIuxwcwy\appProdProjectContainer([
    'container.build_hash' => 'Iuxwcwy',
    'container.build_id' => '9067618a',
    'container.build_time' => 1582612241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuxwcwy');
